### ISSUE TITLE
Can't find labels

### ISSUE THREAD

**Issue by mishraharshit971** [Edoar-do/HuBERT-ECG#2]
I am trying to do inference using the fine-tuned models, but unable to figure out where the labels are mentioned. Please guide where I can find labels. I am using the model "hubert_base_cardio_learning.pt" . Please guide how to know which index in predictions represent which disease.

**Comment by Edoar-do** [comment]
Hello @mishraharshit971!
If you are trying to reproduce the results on the Cardio-Learning dataset, I'm afraid to tell you that this is not possible because a part of Cardio-Learning comes from an access-on-demand dataset that we cannot disclose, as highlighted in the paper.
Otherwise, if you want to use hubert_base_cardio_learning as is, I just added a `cardio-learning-labels.pkl` in the reproducibility folder. This file lists the columns of corresponding dataframe used to reference the Cardio-Learning examples.

Hope this can be enough!
Happy coding and merry Christmas!

EDIT: Thank you for pointing this out!. Providing labels is absolutely necessary for models fine-tuned on Cardio-Learning!
